from .bed import Bed
from .book import Book
from .chair import Chair
from .coffee_cup import CoffeeCup
from .glass_window import GlassWindow
from .lamp import Lamp
from .reading_table import ReadingTable
from .room import Room
from .table_lamp import TableLamp
from .tea_table import TeaTable
